server:
  port : 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rookielessonsbestudent
    username: postgres
    password: djdenis811