# Run as:
# docker-compose -f src\main\resources\codylab-rookie\docker.yaml up
version: "3.7"

services:
  app:
    image: ygmarchi/codylab-rookie:1.0-SNAPSHOT
    # http://localhost:8090/swagger-ui/index.html
    ports:
      - 8090:8081
    environment:
      POSTGRES_HOSTNAME: postgres


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin